/// <mls fileReference="_102050_/l2/cafeFlow/web/shared/dineInOrderLifecycle.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { CafeFlowDineInOrderLifecycleBase } from './dineInOrderLifecycle.js';

type Assignable<Actual, Expected> = Actual extends Expected ? true : false;
type Assert<T extends true> = T;

declare const page: CafeFlowDineInOrderLifecycleBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_createOrderState = Assert<Assignable<typeof page.createOrderState, "idle" | "loading" | "success" | "error">>;
type _State_createOrderOrderType = Assert<Assignable<typeof page.createOrderOrderType, string>>;
type _State_createOrderStatus = Assert<Assignable<typeof page.createOrderStatus, string>>;
type _State_createOrderTotalAmount = Assert<Assignable<typeof page.createOrderTotalAmount, string>>;
type _State_createOrderNotes = Assert<Assignable<typeof page.createOrderNotes, string>>;
type _State_createOrderCustomerName = Assert<Assignable<typeof page.createOrderCustomerName, string>>;
type _State_createOrderCustomerPhone = Assert<Assignable<typeof page.createOrderCustomerPhone, string>>;
type _State_createOrderNumberOfGuests = Assert<Assignable<typeof page.createOrderNumberOfGuests, string>>;
type _State_createOrderClosedAt = Assert<Assignable<typeof page.createOrderClosedAt, string>>;
type _State_createOrderCancelledAt = Assert<Assignable<typeof page.createOrderCancelledAt, string>>;
type _State_createOrderCancellationReason = Assert<Assignable<typeof page.createOrderCancellationReason, string>>;
type _State_addOrderItemState = Assert<Assignable<typeof page.addOrderItemState, "idle" | "loading" | "success" | "error">>;
type _State_addOrderItemQuantity = Assert<Assignable<typeof page.addOrderItemQuantity, string>>;
type _State_addOrderItemUnitPrice = Assert<Assignable<typeof page.addOrderItemUnitPrice, string>>;
type _State_addOrderItemTotalPrice = Assert<Assignable<typeof page.addOrderItemTotalPrice, string>>;
type _State_addOrderItemObservations = Assert<Assignable<typeof page.addOrderItemObservations, string>>;
type _State_addOrderItemStatus = Assert<Assignable<typeof page.addOrderItemStatus, string>>;
type _State_createKitchenTicketState = Assert<Assignable<typeof page.createKitchenTicketState, "idle" | "loading" | "success" | "error">>;
type _State_createKitchenTicketStatus = Assert<Assignable<typeof page.createKitchenTicketStatus, string>>;
type _State_updateOrderStatusState = Assert<Assignable<typeof page.updateOrderStatusState, "idle" | "loading" | "success" | "error">>;
type _State_updateOrderStatusStatus = Assert<Assignable<typeof page.updateOrderStatusStatus, string>>;
type _State_updateOrderStatusClosedAt = Assert<Assignable<typeof page.updateOrderStatusClosedAt, string>>;
type _State_updateOrderStatusCancelledAt = Assert<Assignable<typeof page.updateOrderStatusCancelledAt, string>>;
type _State_updateOrderStatusCancellationReason = Assert<Assignable<typeof page.updateOrderStatusCancellationReason, string>>;
type _State_updateTableStatusState = Assert<Assignable<typeof page.updateTableStatusState, "idle" | "loading" | "success" | "error">>;
type _State_updateTableStatusStatus = Assert<Assignable<typeof page.updateTableStatusStatus, string>>;
type _State_updateTableStatusCurrentChargesTotal = Assert<Assignable<typeof page.updateTableStatusCurrentChargesTotal, string>>;
type _State_updateTableStatusOpenedAt = Assert<Assignable<typeof page.updateTableStatusOpenedAt, string>>;
type _State_updateTableStatusClosedAt = Assert<Assignable<typeof page.updateTableStatusClosedAt, string>>;
type _Action_createOrder = Assert<Assignable<typeof page.createOrder, (...args: any[]) => Promise<void>>>;
type _Handler_handleCreateOrderClick = Assert<Assignable<typeof page.handleCreateOrderClick, (...args: any[]) => void>>;
type _Action_addOrderItem = Assert<Assignable<typeof page.addOrderItem, (...args: any[]) => Promise<void>>>;
type _Handler_handleAddOrderItemClick = Assert<Assignable<typeof page.handleAddOrderItemClick, (...args: any[]) => void>>;
type _Action_createKitchenTicket = Assert<Assignable<typeof page.createKitchenTicket, (...args: any[]) => Promise<void>>>;
type _Handler_handleCreateKitchenTicketClick = Assert<Assignable<typeof page.handleCreateKitchenTicketClick, (...args: any[]) => void>>;
type _Action_updateOrderStatus = Assert<Assignable<typeof page.updateOrderStatus, (...args: any[]) => Promise<void>>>;
type _Handler_handleUpdateOrderStatusClick = Assert<Assignable<typeof page.handleUpdateOrderStatusClick, (...args: any[]) => void>>;
type _Action_updateTableStatus = Assert<Assignable<typeof page.updateTableStatus, (...args: any[]) => Promise<void>>>;
type _Handler_handleUpdateTableStatusClick = Assert<Assignable<typeof page.handleUpdateTableStatusClick, (...args: any[]) => void>>;
type _Action_setCreateOrderOrderType = Assert<Assignable<typeof page.setCreateOrderOrderType, (...args: any[]) => void>>;
type _Handler_handleCreateOrderOrderTypeChange = Assert<Assignable<typeof page.handleCreateOrderOrderTypeChange, (...args: any[]) => void>>;
type _Action_setCreateOrderStatus = Assert<Assignable<typeof page.setCreateOrderStatus, (...args: any[]) => void>>;
type _Handler_handleCreateOrderStatusChange = Assert<Assignable<typeof page.handleCreateOrderStatusChange, (...args: any[]) => void>>;
type _Action_setCreateOrderTotalAmount = Assert<Assignable<typeof page.setCreateOrderTotalAmount, (...args: any[]) => void>>;
type _Handler_handleCreateOrderTotalAmountChange = Assert<Assignable<typeof page.handleCreateOrderTotalAmountChange, (...args: any[]) => void>>;
type _Action_setCreateOrderNotes = Assert<Assignable<typeof page.setCreateOrderNotes, (...args: any[]) => void>>;
type _Handler_handleCreateOrderNotesChange = Assert<Assignable<typeof page.handleCreateOrderNotesChange, (...args: any[]) => void>>;
type _Action_setCreateOrderCustomerName = Assert<Assignable<typeof page.setCreateOrderCustomerName, (...args: any[]) => void>>;
type _Handler_handleCreateOrderCustomerNameChange = Assert<Assignable<typeof page.handleCreateOrderCustomerNameChange, (...args: any[]) => void>>;
type _Action_setCreateOrderCustomerPhone = Assert<Assignable<typeof page.setCreateOrderCustomerPhone, (...args: any[]) => void>>;
type _Handler_handleCreateOrderCustomerPhoneChange = Assert<Assignable<typeof page.handleCreateOrderCustomerPhoneChange, (...args: any[]) => void>>;
type _Action_setCreateOrderNumberOfGuests = Assert<Assignable<typeof page.setCreateOrderNumberOfGuests, (...args: any[]) => void>>;
type _Handler_handleCreateOrderNumberOfGuestsChange = Assert<Assignable<typeof page.handleCreateOrderNumberOfGuestsChange, (...args: any[]) => void>>;
type _Action_setCreateOrderClosedAt = Assert<Assignable<typeof page.setCreateOrderClosedAt, (...args: any[]) => void>>;
type _Handler_handleCreateOrderClosedAtChange = Assert<Assignable<typeof page.handleCreateOrderClosedAtChange, (...args: any[]) => void>>;
type _Action_setCreateOrderCancelledAt = Assert<Assignable<typeof page.setCreateOrderCancelledAt, (...args: any[]) => void>>;
type _Handler_handleCreateOrderCancelledAtChange = Assert<Assignable<typeof page.handleCreateOrderCancelledAtChange, (...args: any[]) => void>>;
type _Action_setCreateOrderCancellationReason = Assert<Assignable<typeof page.setCreateOrderCancellationReason, (...args: any[]) => void>>;
type _Handler_handleCreateOrderCancellationReasonChange = Assert<Assignable<typeof page.handleCreateOrderCancellationReasonChange, (...args: any[]) => void>>;
type _Action_setAddOrderItemQuantity = Assert<Assignable<typeof page.setAddOrderItemQuantity, (...args: any[]) => void>>;
type _Handler_handleAddOrderItemQuantityChange = Assert<Assignable<typeof page.handleAddOrderItemQuantityChange, (...args: any[]) => void>>;
type _Action_setAddOrderItemUnitPrice = Assert<Assignable<typeof page.setAddOrderItemUnitPrice, (...args: any[]) => void>>;
type _Handler_handleAddOrderItemUnitPriceChange = Assert<Assignable<typeof page.handleAddOrderItemUnitPriceChange, (...args: any[]) => void>>;
type _Action_setAddOrderItemTotalPrice = Assert<Assignable<typeof page.setAddOrderItemTotalPrice, (...args: any[]) => void>>;
type _Handler_handleAddOrderItemTotalPriceChange = Assert<Assignable<typeof page.handleAddOrderItemTotalPriceChange, (...args: any[]) => void>>;
type _Action_setAddOrderItemObservations = Assert<Assignable<typeof page.setAddOrderItemObservations, (...args: any[]) => void>>;
type _Handler_handleAddOrderItemObservationsChange = Assert<Assignable<typeof page.handleAddOrderItemObservationsChange, (...args: any[]) => void>>;
type _Action_setAddOrderItemStatus = Assert<Assignable<typeof page.setAddOrderItemStatus, (...args: any[]) => void>>;
type _Handler_handleAddOrderItemStatusChange = Assert<Assignable<typeof page.handleAddOrderItemStatusChange, (...args: any[]) => void>>;
type _Action_setCreateKitchenTicketStatus = Assert<Assignable<typeof page.setCreateKitchenTicketStatus, (...args: any[]) => void>>;
type _Handler_handleCreateKitchenTicketStatusChange = Assert<Assignable<typeof page.handleCreateKitchenTicketStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateOrderStatusStatus = Assert<Assignable<typeof page.setUpdateOrderStatusStatus, (...args: any[]) => void>>;
type _Handler_handleUpdateOrderStatusStatusChange = Assert<Assignable<typeof page.handleUpdateOrderStatusStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateOrderStatusClosedAt = Assert<Assignable<typeof page.setUpdateOrderStatusClosedAt, (...args: any[]) => void>>;
type _Handler_handleUpdateOrderStatusClosedAtChange = Assert<Assignable<typeof page.handleUpdateOrderStatusClosedAtChange, (...args: any[]) => void>>;
type _Action_setUpdateOrderStatusCancelledAt = Assert<Assignable<typeof page.setUpdateOrderStatusCancelledAt, (...args: any[]) => void>>;
type _Handler_handleUpdateOrderStatusCancelledAtChange = Assert<Assignable<typeof page.handleUpdateOrderStatusCancelledAtChange, (...args: any[]) => void>>;
type _Action_setUpdateOrderStatusCancellationReason = Assert<Assignable<typeof page.setUpdateOrderStatusCancellationReason, (...args: any[]) => void>>;
type _Handler_handleUpdateOrderStatusCancellationReasonChange = Assert<Assignable<typeof page.handleUpdateOrderStatusCancellationReasonChange, (...args: any[]) => void>>;
type _Action_setUpdateTableStatusStatus = Assert<Assignable<typeof page.setUpdateTableStatusStatus, (...args: any[]) => void>>;
type _Handler_handleUpdateTableStatusStatusChange = Assert<Assignable<typeof page.handleUpdateTableStatusStatusChange, (...args: any[]) => void>>;
type _Action_setUpdateTableStatusCurrentChargesTotal = Assert<Assignable<typeof page.setUpdateTableStatusCurrentChargesTotal, (...args: any[]) => void>>;
type _Handler_handleUpdateTableStatusCurrentChargesTotalChange = Assert<Assignable<typeof page.handleUpdateTableStatusCurrentChargesTotalChange, (...args: any[]) => void>>;
type _Action_setUpdateTableStatusOpenedAt = Assert<Assignable<typeof page.setUpdateTableStatusOpenedAt, (...args: any[]) => void>>;
type _Handler_handleUpdateTableStatusOpenedAtChange = Assert<Assignable<typeof page.handleUpdateTableStatusOpenedAtChange, (...args: any[]) => void>>;
type _Action_setUpdateTableStatusClosedAt = Assert<Assignable<typeof page.setUpdateTableStatusClosedAt, (...args: any[]) => void>>;
type _Handler_handleUpdateTableStatusClosedAtChange = Assert<Assignable<typeof page.handleUpdateTableStatusClosedAtChange, (...args: any[]) => void>>;

export {};