/// <mls fileReference="_102050_/l2/controleChamados/web/shared/ticketCatalogue.test.ts" enhancement="_102020_/l2/enhancementAura"/>

import type { ControleChamadosTicketCatalogueBase } from '/_102050_/l2/controleChamados/web/shared/ticketCatalogue.js';
import type { CmdCreateTicketInput, CmdCreateTicketOutput, CmdDecideClosureInput, CmdDecideClosureOutput, CmdDeleteTicketInput, CmdDeleteTicketOutput, CmdUpdateTicketInput, CmdUpdateTicketOutput, QryGetTicketInput, QryGetTicketOutput, QryListTicketInput, QryListTicketOutput, QryLocateTicketOutput } from '/_102050_/l2/controleChamados/web/contracts/ticketCatalogue.js';

type IsAny<T> = 0 extends (1 & T) ? true : false;
type Assignable<Actual, Expected> = IsAny<Actual> extends true ? false : [Actual] extends [Expected] ? true : false;
type Assert<T extends true> = T;

declare const page: ControleChamadosTicketCatalogueBase;

// This file is generated from .defs.ts. Add narrower state/action assertions here as materialization rules evolve.
type _State_status = Assert<Assignable<typeof page.status, string>>;
type _State_uiScenary = Assert<Assignable<typeof page.uiScenary, "base" | "detail" | "createTicket" | "updateTicket" | "decideClosure">>;
type _State_qryListTicketState = Assert<Assignable<typeof page.qryListTicketState, "idle" | "loading" | "success" | "error">>;
type _State_qryListTicketSearch = Assert<Assignable<typeof page.qryListTicketSearch, string | QryListTicketInput["search"]>>;
type _State_qryListTicketSortBy = Assert<Assignable<typeof page.qryListTicketSortBy, "open" | "closed" | QryListTicketInput["sortBy"] | ''>>;
type _State_qryListTicketSortOrder = Assert<Assignable<typeof page.qryListTicketSortOrder, "asc" | "desc" | QryListTicketInput["sortOrder"] | ''>>;
type _State_qryListTicketData = Assert<Assignable<typeof page.qryListTicketData, unknown[] | QryListTicketOutput>>;
type _State_cmdCreateTicketState = Assert<Assignable<typeof page.cmdCreateTicketState, "idle" | "loading" | "success" | "error">>;
type _State_cmdCreateTicketTitle = Assert<Assignable<typeof page.cmdCreateTicketTitle, string | CmdCreateTicketInput["title"]>>;
type _State_cmdCreateTicketDescription = Assert<Assignable<typeof page.cmdCreateTicketDescription, string | CmdCreateTicketInput["description"]>>;
type _State_cmdCreateTicketStatus = Assert<Assignable<typeof page.cmdCreateTicketStatus, "open" | "closed" | CmdCreateTicketInput["status"] | ''>>;
type _State_cmdCreateTicketOutput = Assert<Assignable<typeof page.cmdCreateTicketOutput, CmdCreateTicketOutput | null>>;
type _State_cmdCreateTicketError = Assert<Assignable<typeof page.cmdCreateTicketError, string>>;
type _State_cmdUpdateTicketState = Assert<Assignable<typeof page.cmdUpdateTicketState, "idle" | "loading" | "success" | "error">>;
type _State_cmdUpdateTicketTicketId = Assert<Assignable<typeof page.cmdUpdateTicketTicketId, string | CmdUpdateTicketInput["ticketId"]>>;
type _State_cmdUpdateTicketTitle = Assert<Assignable<typeof page.cmdUpdateTicketTitle, string | CmdUpdateTicketInput["title"]>>;
type _State_cmdUpdateTicketDescription = Assert<Assignable<typeof page.cmdUpdateTicketDescription, string | CmdUpdateTicketInput["description"]>>;
type _State_cmdUpdateTicketStatus = Assert<Assignable<typeof page.cmdUpdateTicketStatus, "open" | "closed" | CmdUpdateTicketInput["status"] | ''>>;
type _State_cmdUpdateTicketOutput = Assert<Assignable<typeof page.cmdUpdateTicketOutput, CmdUpdateTicketOutput | null>>;
type _State_cmdUpdateTicketError = Assert<Assignable<typeof page.cmdUpdateTicketError, string>>;
type _State_cmdDeleteTicketState = Assert<Assignable<typeof page.cmdDeleteTicketState, "idle" | "loading" | "success" | "error">>;
type _State_cmdDeleteTicketTicketId = Assert<Assignable<typeof page.cmdDeleteTicketTicketId, string | CmdDeleteTicketInput["ticketId"]>>;
type _State_cmdDeleteTicketOutput = Assert<Assignable<typeof page.cmdDeleteTicketOutput, CmdDeleteTicketOutput | null>>;
type _State_cmdDeleteTicketError = Assert<Assignable<typeof page.cmdDeleteTicketError, string>>;
type _State_qryGetTicketState = Assert<Assignable<typeof page.qryGetTicketState, "idle" | "loading" | "success" | "error">>;
type _State_qryGetTicketTicketId = Assert<Assignable<typeof page.qryGetTicketTicketId, string | QryGetTicketInput["ticketId"]>>;
type _State_qryGetTicketData = Assert<Assignable<typeof page.qryGetTicketData, QryGetTicketOutput | null>>;
type _State_qryLocateTicketState = Assert<Assignable<typeof page.qryLocateTicketState, "idle" | "loading" | "success" | "error">>;
type _State_qryLocateTicketData = Assert<Assignable<typeof page.qryLocateTicketData, unknown[] | QryLocateTicketOutput>>;
type _State_cmdDecideClosureState = Assert<Assignable<typeof page.cmdDecideClosureState, "idle" | "loading" | "success" | "error">>;
type _State_cmdDecideClosureTicketId = Assert<Assignable<typeof page.cmdDecideClosureTicketId, string | CmdDecideClosureInput["ticketId"]>>;
type _State_cmdDecideClosureStatus = Assert<Assignable<typeof page.cmdDecideClosureStatus, "open" | "closed" | CmdDecideClosureInput["status"] | ''>>;
type _State_cmdDecideClosureOutput = Assert<Assignable<typeof page.cmdDecideClosureOutput, CmdDecideClosureOutput | null>>;
type _State_cmdDecideClosureError = Assert<Assignable<typeof page.cmdDecideClosureError, string>>;
type _Action_loadQryListTicket = Assert<Assignable<typeof page.loadQryListTicket, (...args: any[]) => unknown>>;
type _Handler_handleQryListTicketClick = Assert<Assignable<typeof page.handleQryListTicketClick, (...args: any[]) => unknown>>;
type _Action_cmdCreateTicket = Assert<Assignable<typeof page.cmdCreateTicket, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateTicketClick = Assert<Assignable<typeof page.handleCmdCreateTicketClick, (...args: any[]) => unknown>>;
type _Action_cmdUpdateTicket = Assert<Assignable<typeof page.cmdUpdateTicket, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateTicketClick = Assert<Assignable<typeof page.handleCmdUpdateTicketClick, (...args: any[]) => unknown>>;
type _Action_cmdDeleteTicket = Assert<Assignable<typeof page.cmdDeleteTicket, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteTicketClick = Assert<Assignable<typeof page.handleCmdDeleteTicketClick, (...args: any[]) => unknown>>;
type _Action_loadQryGetTicket = Assert<Assignable<typeof page.loadQryGetTicket, (...args: any[]) => unknown>>;
type _Handler_handleQryGetTicketClick = Assert<Assignable<typeof page.handleQryGetTicketClick, (...args: any[]) => unknown>>;
type _Action_loadQryLocateTicket = Assert<Assignable<typeof page.loadQryLocateTicket, (...args: any[]) => unknown>>;
type _Handler_handleQryLocateTicketClick = Assert<Assignable<typeof page.handleQryLocateTicketClick, (...args: any[]) => unknown>>;
type _Action_cmdDecideClosure = Assert<Assignable<typeof page.cmdDecideClosure, (...args: any[]) => unknown>>;
type _Handler_handleCmdDecideClosureClick = Assert<Assignable<typeof page.handleCmdDecideClosureClick, (...args: any[]) => unknown>>;
type _Action_setQryListTicketSearch = Assert<Assignable<typeof page.setQryListTicketSearch, (...args: any[]) => unknown>>;
type _Handler_handleQryListTicketSearchChange = Assert<Assignable<typeof page.handleQryListTicketSearchChange, (...args: any[]) => unknown>>;
type _Action_setQryListTicketSortBy = Assert<Assignable<typeof page.setQryListTicketSortBy, (...args: any[]) => unknown>>;
type _Handler_handleQryListTicketSortByChange = Assert<Assignable<typeof page.handleQryListTicketSortByChange, (...args: any[]) => unknown>>;
type _Action_setQryListTicketSortOrder = Assert<Assignable<typeof page.setQryListTicketSortOrder, (...args: any[]) => unknown>>;
type _Handler_handleQryListTicketSortOrderChange = Assert<Assignable<typeof page.handleQryListTicketSortOrderChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateTicketTitle = Assert<Assignable<typeof page.setCmdCreateTicketTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateTicketTitleChange = Assert<Assignable<typeof page.handleCmdCreateTicketTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateTicketDescription = Assert<Assignable<typeof page.setCmdCreateTicketDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateTicketDescriptionChange = Assert<Assignable<typeof page.handleCmdCreateTicketDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdCreateTicketStatus = Assert<Assignable<typeof page.setCmdCreateTicketStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdCreateTicketStatusChange = Assert<Assignable<typeof page.handleCmdCreateTicketStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateTicketTicketId = Assert<Assignable<typeof page.setCmdUpdateTicketTicketId, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateTicketTicketIdChange = Assert<Assignable<typeof page.handleCmdUpdateTicketTicketIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateTicketTitle = Assert<Assignable<typeof page.setCmdUpdateTicketTitle, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateTicketTitleChange = Assert<Assignable<typeof page.handleCmdUpdateTicketTitleChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateTicketDescription = Assert<Assignable<typeof page.setCmdUpdateTicketDescription, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateTicketDescriptionChange = Assert<Assignable<typeof page.handleCmdUpdateTicketDescriptionChange, (...args: any[]) => unknown>>;
type _Action_setCmdUpdateTicketStatus = Assert<Assignable<typeof page.setCmdUpdateTicketStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdUpdateTicketStatusChange = Assert<Assignable<typeof page.handleCmdUpdateTicketStatusChange, (...args: any[]) => unknown>>;
type _Action_setCmdDeleteTicketTicketId = Assert<Assignable<typeof page.setCmdDeleteTicketTicketId, (...args: any[]) => unknown>>;
type _Handler_handleCmdDeleteTicketTicketIdChange = Assert<Assignable<typeof page.handleCmdDeleteTicketTicketIdChange, (...args: any[]) => unknown>>;
type _Action_setQryGetTicketTicketId = Assert<Assignable<typeof page.setQryGetTicketTicketId, (...args: any[]) => unknown>>;
type _Handler_handleQryGetTicketTicketIdChange = Assert<Assignable<typeof page.handleQryGetTicketTicketIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdDecideClosureTicketId = Assert<Assignable<typeof page.setCmdDecideClosureTicketId, (...args: any[]) => unknown>>;
type _Handler_handleCmdDecideClosureTicketIdChange = Assert<Assignable<typeof page.handleCmdDecideClosureTicketIdChange, (...args: any[]) => unknown>>;
type _Action_setCmdDecideClosureStatus = Assert<Assignable<typeof page.setCmdDecideClosureStatus, (...args: any[]) => unknown>>;
type _Handler_handleCmdDecideClosureStatusChange = Assert<Assignable<typeof page.handleCmdDecideClosureStatusChange, (...args: any[]) => unknown>>;

export {};